server:
  port: 8080 #8080포트 사용
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: subway-2
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql설정
    url: jdbc:mysql://localhost:3306/SubwayStationInfo?createDatabaseIfNotExist=true #스키마는 본인이 설정하고 싶은 이름으로 넣으면 된다.
    username: root
    password: root
  profiles:
    active: local

  jpa: #jap 설정
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rest:
    ignore_ssl : true